version: '3'
services:
    web:
        image: php:7.2-apache
        working_dir: /var/www/html
        ports:
            - 8080:80
        volumes: 
            - .:/var/www/html
            - ./init.sh:/docker-entrypoint-initdb.d/init.sh
        entrypoint:
            - /bin/sh
            - /docker-entrypoint-initdb.d/init.sh
